services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./app:/var/www:cached
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=convenia
      - DB_USERNAME=convenia-user
      - DB_PASSWORD="6AbP7CB!HH7t"
    networks:
      - laravel-network
    user: "1000:1000" 

  webserver:
    image: nginx:alpine
    container_name: webserver
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: convenia
      MYSQL_USER: convenia-user
      MYSQL_PASSWORD: "6AbP7CB!HH7t"
      MYSQL_ROOT_PASSWORD: "6AbP7CB!HH7t"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-network

volumes:
  mysql-data:

networks:
  laravel-network:
    driver: bridge